version: 2

defaults: &defaults
  docker:
    - image: hashicorp/terraform

jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Terraform Init
          command: terraform init
  plan:
    steps:
      - checkout
      - run: 
          name: Terraform Plan
          command: terraform plan
    

workflows:
  version: 2
  build:
    jobs:
      - init
      - plan:
          requires:
            - init