version: 2

defaults: &defaults
  working_directory: ~/circleci-training
  docker:
    - image: hashicorp/terraform
  environment:
    TF_IN_AUTOMATION: true

jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Terraform Init
          command: terraform init -input=false
      - persist_to_workspace:
          root: ~/circleci-training
          paths: .
  plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-training
      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan  -input=false
      - store_artifacts:
          path: ~/circleci-training/tfplan
          destination: tfplan
      - persist_to_workspace:
          root: ~/circleci-training
          paths: .
  apply:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-training
      - run:
          name: Terraform Apply
          command: terraform apply -input=false -auto-approve tfplan
      - run:
          name: Show
          command: terraform show  > tfresult
      - store_artifacts:
          path: ~/circleci-training/tfresult
          destination: tfresult
  destroy:
    <<: *defaults
    steps:
      - run:
          name: Terraform destroy
          command: terraform destroy --auto-approve

workflows:
  version: 2
  build_deploy:
    jobs:
      - init
      - plan:
          requires:
            - init
      - hold:
          type: approval
          requires:
            - plan
      - apply:
          requires:
            - plan
          filters:
            branches:
              only:
                - master
      - destroy:
          requires:
            - hold
