version: 2

defaults: &defaults
  working_directory: ~/circleci-training
  docker:
    - image: hashicorp/terraform
  environment:
    TF_IN_AUTOMATION: true

jobs:
  init:
    <<: *defaults
    steps:
      - checkout
      - run: 
          name: Terraform Init
          command: terraform init
      - persist_to_workspace:
            root: ~/circleci-training
            paths: .
  plan:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/circleci-training
      - run: 
          name: Terraform Plan
          command: terraform plan
    

workflows:
  version: 2
  build_deploy:
    jobs:
      - init
      - plan:
          requires:
            - init